# Generated by Django 4.0.4 on 2022-07-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_user_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.BigIntegerField(default=None),
        ),
    ]
