# Generated by Django 4.0.4 on 2022-07-29 04:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_remove_user_password_alter_user_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabet characters are allowed.')]),
        ),
    ]
